team_to_state_mapping = {
    'Royal Challengers Bangalore': 'RCB',
    'Kings XI Punjab': 'PUNJAB',
    'Delhi Daredevils': "DC",
    'Mumbai Indians': 'MI',
    'Kolkata Knight Riders': 'KKR',
    'Rajasthan Royals': 'RR',
    'Deccan Chargers': 'SRH',
    'Chennai Super Kings': 'CSK',
    'Kochi Tuskers Kerala': 'KERALA',
    'Pune Warriors': 'PUNE',
    'Sunrisers Hyderabad': 'SRH',
    'Gujarat Lions': 'GT',
    'Rising Pune Supergiants': 'PUNE',
    'Rising Pune Supergiant': 'PUNE',
    'Delhi Capitals': 'DC',
    'Punjab Kings': 'PUNJAB',
    'Lucknow Super Giants': 'LSG',
    'Gujarat Titans': 'GT',
    'Royal Challengers Bengaluru': 'RCB'
}